### ISSUE TITLE
Run Time error 13

### ISSUE THREAD

**Issue by viaj3ro** [STAWKEYE/LightningNodeStats#1]
When I click the `READ API DATA` button it successfully reads all my channels but after a while it fails due to  

`Run-time error '13':`
`Type mismatch`

when I klick `debug` it highlights this line:

`Worksheets("Channel Watchlist").Cells(i, 6) = Worksheets("Dashboard").Cells(j, 5) * Worksheets("Dashboard").Cells(35, 22)`

from this section of the code:

```
'Run through Channel watchlist
'Delete closed nodes, or nodes in NORMAL state, from Channel watchlist
For i = 2 To lastbadchannel
    Del = 1
    For j = 2 To totalChannels
        'If you find matching ChannelID and it's not in NORMAL state, keep it.
        If Worksheets("Channel Watchlist").Cells(i, 3) = Worksheets("Dashboard").Cells(j, 3) And Worksheets("Dashboard").Cells(j, 4) <> "NORMAL" Then
            Del = 0
            'Update Locked Funds if channel is not NORMAL
            Worksheets("Channel Watchlist").Cells(i, 6) = Worksheets("Dashboard").Cells(j, 5) * Worksheets("Dashboard").Cells(35, 22)
            'If the channel is not NORMAL but there has been an update to the status, reset status and date
            If Worksheets("Channel Watchlist").Cells(i, 4) <> Worksheets("Dashboard").Cells(j, 4) Then
                Worksheets("Channel Watchlist").Cells(i, 4) = Worksheets("Dashboard").Cells(j, 4)
                Worksheets("Channel Watchlist").Cells(i, 5) = Date
            End If
        End If
    Next j
    If Del = 1 And Worksheets("Channel Watchlist").Cells(i, 2) <> "" Then
        Worksheets("Channel Watchlist").Rows(i).Delete
        i = i - 1
    End If
Next i

```

Any Idea, what the issue is? 

The spreadsheet looks like this:

https://imgur.com/tbTEkHB

**Comment by STAWKEYE** [comment]
That line is trying to read the current BTC price, but you have a NAME error in cell V35, which is Worksheets("Dashboard").Cells(35, 22).
Make sure it has the following formula - I had to change quote providers when the previous one shut off its API. I may not have updated it on GitHub - I'll have to check.
=VALUE(WEBSERVICE("https://api.coingate.com/v2/rates/merchant/BTC/USD"))

**Comment by STAWKEYE** [comment]
Error was caused by https://github.com/STAWKEYE/LightningNodeStats/issues/2
